# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import asyncio
from contextlib import asynccontextmanager
from dataclasses import dataclass
from dataclasses import field
from typing import AsyncIterator
from uuid import UUID

import structlog
from fastapi import FastAPI
from httpx import AsyncClient

from .autogenerated_graphql_client import GraphQLClient
from .autogenerated_graphql_client import ListenerCreateInput
from .autogenerated_graphql_client import NamespaceCreateInput
from .config import Settings
from .context import Context

logger = structlog.stdlib.get_logger()


@dataclass
class Namespace:
    name: str
    public: bool = False


@dataclass
class Listener:
    namespace: str
    user_key: str
    routing_key: str
    url: str
    # TODO: timeout?


@dataclass
class GraphQLEvents:
    namespaces: list[Namespace] = field(default_factory=list)
    listeners: list[Listener] = field(default_factory=list)


async def fetcher(
    app: FastAPI, client: GraphQLClient, listener: UUID, url: str
) -> None:
    logger.debug("Starting fetcher", listener=listener)
    while True:
        event = await client.fetch_event(listener)
        logger.debug("Fetched event", graphql_event=event)
        if event is None:
            await asyncio.sleep(5)
            continue
        try:
            print(event)
            r = await AsyncClient(app=app, base_url="http://localhost", timeout=5).post(
                url,
                # TODO: make into a model, importable from integrations
                json={
                    "subject": event.subject,
                    "priority": event.priority,
                },
            )
            r.raise_for_status()
            await client.acknowledge_event(event.token)
        except Exception:
            logger.exception("ARGH!")


@asynccontextmanager
async def lifespan(
    app: FastAPI, settings: Settings, context: Context, events: GraphQLEvents
) -> AsyncIterator[None]:
    graphql_client = GraphQLClient(
        url=f"{settings.mo_url}/graphql/v25",
        http_client=context["mo_client"],
    )
    async with graphql_client as client:
        for namespace in events.namespaces:
            logger.info("Declaring namespace", namespace=namespace)
            await client.declare_event_namespace(
                input=NamespaceCreateInput(
                    name=namespace.name,
                    public=namespace.public,
                )
            )
        for listener in events.listeners:
            logger.info("Declaring listener", listener=listener)
            graphql_listener = await client.declare_event_listener(
                input=ListenerCreateInput(
                    namespace=listener.namespace,
                    user_key=listener.user_key,
                    routing_key=listener.routing_key,
                )
            )
            asyncio.create_task(
                fetcher(app, client, graphql_listener.uuid, listener.url)
            )
        yield
