# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

import asyncio

import pytest
from fastapi import APIRouter
from starlette.testclient import TestClient

from fastramqpi.autogenerated_graphql_client import EventSendInput
from fastramqpi.autogenerated_graphql_client import GraphQLClient
from fastramqpi.events import Event
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.events import Namespace
from fastramqpi.main import FastRAMQPI
from tests.fastramqpi.integration.conftest import Settings


@pytest.mark.integration_test
async def test_events() -> None:
    fastramqpi = FastRAMQPI(
        application_name="os2mo-test-integration",
        settings=Settings().fastramqpi,
        graphql_version=25,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(
            declare_namespaces=[
                Namespace(name="🌌"),
            ],
            declare_listeners=[
                Listener(
                    namespace="🌌",
                    user_key="test-listener",
                    routing_key="🔑",
                    path="/handler",
                ),
            ],
        ),
    )
    app = fastramqpi.get_app()

    router = APIRouter()
    received_events = []
    done = asyncio.Event()

    @router.post("/handler")
    async def handler(event: Event) -> None:
        received_events.append(event)
        done.set()

    app.include_router(router)

    with TestClient(app):
        graphql_client: GraphQLClient = app.state.context["graphql_client"]
        await graphql_client._testing__send_event(
            input=EventSendInput(
                namespace="🌌",
                routing_key="🔑",
                subject="✉️",
                priority=1337,
            )
        )
        await asyncio.wait_for(done.wait(), timeout=10)
        assert received_events == [
            Event(
                subject="✉️",
                priority=1337,
            )
        ]
