# Generated by ariadne-codegen on 2025-04-29 16:55
# Source: queries.graphql

from .base_model import BaseModel


class TestingSendEvent(BaseModel):
    event_send: bool


TestingSendEvent.update_forward_refs()
