# Generated by ariadne-codegen on 2025-04-23 13:23
# Source: queries.graphql

from .base_model import BaseModel


class AcknowledgeEvent(BaseModel):
    event_acknowledge: bool


AcknowledgeEvent.update_forward_refs()
