# Generated by ariadne-codegen on 2025-04-16 18:53
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class AcknowledgeEvent(BaseModel):
    event_acknowledge: Optional[Any]


AcknowledgeEvent.update_forward_refs()
