# Generated by ariadne-codegen on 2025-04-23 13:23
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class DeclareEventListener(BaseModel):
    event_listener_declare: "DeclareEventListenerEventListenerDeclare"


class DeclareEventListenerEventListenerDeclare(BaseModel):
    uuid: UUID


DeclareEventListener.update_forward_refs()
DeclareEventListenerEventListenerDeclare.update_forward_refs()
