# Generated by ariadne-codegen on 2025-04-23 13:23
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class FetchEvent(BaseModel):
    event_fetch: Optional["FetchEventEventFetch"]


class FetchEventEventFetch(BaseModel):
    subject: str
    priority: int
    token: Any


FetchEvent.update_forward_refs()
FetchEventEventFetch.update_forward_refs()
